spring:
  application:
    name: log-handler
  data:
    mongodb:
      host: 172.16.47.47
      port: 27017
      database: logs
  kafka:
      bootstrap-servers: 172.16.47.47:9092
      consumer:
          group-id: log-handler
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          auto-offset-reset: earliest
          enable-auto-commit: true

server:
  port: 8084 
  
kafka:
    topic:
        readingLog: reading_log  
