
spring:
  application:
    name: log-creator
  kafka:
      bootstrap-servers: 172.22.47.47:9092
      producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer   


server:
  port: 8082 
  
kafka:
    topic:
        createLog: create_log          