spring:
  application:
    name: central-server
  kafka:
      bootstrap-servers: 172.16.47.47:9092
      consumer:
          group-id: central-server
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          auto-offset-reset: earliest
          enable-auto-commit: true  

server:
  port: 8083 
  
kafka:
    topic:
        createLog: create_log             