spring:
  application:
    name: log-listener
  kafka:
      bootstrap-servers: 172.16.47.47:9092
      producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8085 
  
kafka:
    topic:
        readingLog: reading_log                   