spring:
  application:
    name: log-listener
  data:
    mongodb:
      host: 172.16.47.47
      port: 27017
      database: log-listener
  kafka:
      bootstrap-servers: 172.16.47.47:9092
      producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      consumer:
          group-id: log-listener
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          auto-offset-reset: earliest
          enable-auto-commit: true

server:
  port: 8084 
  
kafka:
    topic:
        readingLog: reading_log                   